//! Deterministic C header generation for DISP's defined C ABI v1 contract.

use super::{layout, native_types, target::Target};
use crate::{
    diagnostics::{Diagnostic, DiagnosticKind, Span},
    freestanding::transactional_write,
    hir, limits,
};
use std::{
    collections::HashSet,
    fmt::Write,
    path::{Path, PathBuf},
};

pub const ABI_VERSION: u32 = 1;

pub fn generate(program: &hir::Program) -> Result<String, Diagnostic> {
    let external = program
        .functions
        .iter()
        .filter(|function| function.external.is_some())
        .collect::<Vec<_>>();
    let exported = program
        .functions
        .iter()
        .filter(|function| function.exported)
        .collect::<Vec<_>>();
    let mut pointers = Vec::<hir::Type>::new();
    let mut callbacks = Vec::<hir::Type>::new();
    for declaration in program
        .structs
        .iter()
        .filter(|declaration| declaration.c_abi)
    {
        for field in &declaration.fields {
            collect_pointer_types(program, &field.ty, &mut pointers)?;
            collect_callback_types(program, &field.ty, &mut callbacks)?;
        }
    }
    for function in &external {
        for local in &function.parameters {
            let ty = &program.functions[function.id.0].locals[local.0].ty;
            collect_pointer_types(program, ty, &mut pointers)?;
            collect_callback_types(program, ty, &mut callbacks)?;
        }
        collect_pointer_types(program, &function.return_type, &mut pointers)?;
        collect_callback_types(program, &function.return_type, &mut callbacks)?;
    }
    for function in &exported {
        for local in &function.parameters {
            let ty = &function.locals[local.0].ty;
            collect_pointer_types(program, ty, &mut pointers)?;
            collect_callback_types(program, ty, &mut callbacks)?;
        }
        collect_pointer_types(program, &function.return_type, &mut pointers)?;
        collect_callback_types(program, &function.return_type, &mut callbacks)?;
    }
    pointers.sort_by_key(|ty| (pointer_depth(ty), type_code(ty)));
    pointers.dedup();
    callbacks.sort_by_key(|ty| (callback_depth(ty), type_code(ty)));
    callbacks.dedup();

    let mut output = format!(
        "/* Generated by DISP. Do not edit. */\n\
         #ifndef DISP_C_ABI_V1_H\n\
         #define DISP_C_ABI_V1_H\n\
         #include <stdbool.h>\n\
         #include <stddef.h>\n\
         #include <stdint.h>\n\
         #include <limits.h>\n\
         #define DISP_C_ABI_VERSION {ABI_VERSION}u\n\
         #if CHAR_BIT != 8\n\
         #error \"DISP C ABI requires 8-bit bytes\"\n\
         #endif\n\
         #if defined(__cplusplus)\n\
         extern \"C\" {{\n\
         #endif\n\
         #if defined(__cplusplus)\n\
         static_assert(sizeof(bool) == 1, \"DISP bool ABI mismatch\");\n\
         #define DISP_C_STATIC_ASSERT(condition, message) static_assert(condition, message)\n\
         #define DISP_C_ALIGNOF(type) alignof(type)\n\
         #else\n\
         _Static_assert(sizeof(bool) == 1, \"DISP bool ABI mismatch\");\n\
         #define DISP_C_STATIC_ASSERT(condition, message) _Static_assert(condition, message)\n\
         #define DISP_C_ALIGNOF(type) _Alignof(type)\n\
         #endif\n"
    );
    for declaration in program
        .structs
        .iter()
        .filter(|declaration| declaration.c_abi)
    {
        let public_name = record_name(declaration)?;
        let storage_name = native_types::name(&hir::Type::Struct(declaration.id, Vec::new()));
        writeln!(
            output,
            "typedef struct {storage_name} {storage_name};\ntypedef {storage_name} {public_name};"
        )
        .unwrap();
    }
    for pointer in &pointers {
        let hir::Type::RawPointer { mutable, inner } = pointer else {
            unreachable!("pointer collection returns only raw pointers")
        };
        writeln!(
            output,
            "typedef {}{} *{};",
            if *mutable { "" } else { "const " },
            c_type(program, inner)?,
            pointer_name(pointer)?
        )
        .unwrap();
    }
    emit_record_definitions(program, &mut output)?;
    for callback in &callbacks {
        let hir::Type::CFunction(parameters, result) = callback else {
            unreachable!()
        };
        write!(
            output,
            "typedef {} (*{})(",
            c_result(program, result)?,
            callback_name(callback)?
        )
        .unwrap();
        if parameters.is_empty() {
            output.push_str("void");
        } else {
            for (index, parameter) in parameters.iter().enumerate() {
                if index > 0 {
                    output.push_str(", ");
                }
                output.push_str(&c_type(program, parameter)?);
            }
        }
        output.push_str(");\n");
    }
    for function in external {
        let metadata = function.external.as_ref().unwrap();
        writeln!(
            output,
            "/* DISP library: {} */",
            metadata.library.as_deref().unwrap_or("process")
        )
        .unwrap();
        write!(
            output,
            "{} {}(",
            c_result(program, &function.return_type)?,
            metadata.link_name
        )
        .unwrap();
        if function.parameters.is_empty() {
            output.push_str("void");
        } else {
            for (index, local) in function.parameters.iter().enumerate() {
                if index > 0 {
                    output.push_str(", ");
                }
                write!(
                    output,
                    "{} arg{}",
                    c_type(program, &function.locals[local.0].ty)?,
                    index + 1
                )
                .unwrap();
            }
        }
        output.push_str(");\n");
    }
    if !exported.is_empty() {
        output.push_str(
            "#define DISP_C_STATUS_OK 0\n\
             #define DISP_C_STATUS_PANIC 1\n\
             #define DISP_C_STATUS_INVALID_ARGUMENT 2\n\
             #define DISP_C_STATUS_THREAD_NOT_ATTACHED 3\n\
             #define DISP_C_STATUS_THREAD_ALREADY_ATTACHED 4\n\
             #define DISP_C_STATUS_THREAD_BUSY 5\n\
             #if defined(_WIN32)\n\
             #define DISP_C_API __declspec(dllimport)\n\
             #else\n\
             #define DISP_C_API __attribute__((visibility(\"default\")))\n\
             #endif\n\
             DISP_C_API const char *disp_c_last_error(void);\n\
             DISP_C_API int32_t disp_c_thread_attach(void);\n\
             DISP_C_API int32_t disp_c_thread_detach(void);\n",
        );
    }
    for function in exported {
        write!(
            output,
            "typedef int32_t (*disp_c_callback_{})(",
            function.name
        )
        .unwrap();
        write_export_parameters(program, &mut output, function)?;
        output.push_str(");\n");
        write!(output, "DISP_C_API int32_t {}(", function.name).unwrap();
        write_export_parameters(program, &mut output, function)?;
        output.push_str(");\n");
    }
    output.push_str(
        "#undef DISP_C_ALIGNOF\n\
         #undef DISP_C_STATIC_ASSERT\n\
         #if defined(__cplusplus)\n\
         }\n\
         #endif\n\
         #endif /* DISP_C_ABI_V1_H */\n",
    );
    if output.len() > limits::MAX_GENERATED_HEADER_BYTES {
        return Err(error("generated C header exceeds the 16 MiB safety limit"));
    }
    Ok(output)
}

fn write_export_parameters(
    program: &hir::Program,
    output: &mut String,
    function: &hir::Function,
) -> Result<(), Diagnostic> {
    let mut count = 0usize;
    for (index, local) in function.parameters.iter().enumerate() {
        if count > 0 {
            output.push_str(", ");
        }
        write!(
            output,
            "{} arg{}",
            c_type(program, &function.locals[local.0].ty)?,
            index + 1
        )
        .unwrap();
        count += 1;
    }
    if !matches!(function.return_type, hir::Type::Unit) {
        if count > 0 {
            output.push_str(", ");
        }
        write!(
            output,
            "{} *out_result",
            c_type(program, &function.return_type)?
        )
        .unwrap();
        count += 1;
    }
    if count == 0 {
        output.push_str("void");
    }
    Ok(())
}

pub fn destination(source: &Path) -> PathBuf {
    if source.is_dir() {
        source.join("disp_ffi_v1.h")
    } else {
        source.with_extension("h")
    }
}

pub fn write(program: &hir::Program, source: &Path) -> Result<PathBuf, Diagnostic> {
    let output = destination(source);
    let header = generate(program)?;
    transactional_write(&output, header.as_bytes()).map_err(|cause| {
        error(&format!(
            "could not transactionally write C header `{}`: {cause}",
            output.display()
        ))
    })?;
    Ok(output)
}

fn collect_pointer_types(
    program: &hir::Program,
    ty: &hir::Type,
    output: &mut Vec<hir::Type>,
) -> Result<(), Diagnostic> {
    if let hir::Type::RawPointer { inner, .. } = ty {
        collect_pointer_types(program, inner, output)?;
        c_type(program, inner)?;
        output.push(ty.clone());
    } else if let hir::Type::CFunction(parameters, result) = ty {
        for parameter in parameters {
            collect_pointer_types(program, parameter, output)?;
        }
        collect_pointer_types(program, result, output)?;
    } else {
        c_type(program, ty)?;
    }
    Ok(())
}

fn collect_callback_types(
    program: &hir::Program,
    ty: &hir::Type,
    output: &mut Vec<hir::Type>,
) -> Result<(), Diagnostic> {
    match ty {
        hir::Type::CFunction(parameters, result) => {
            for parameter in parameters {
                collect_callback_types(program, parameter, output)?;
            }
            collect_callback_types(program, result, output)?;
            output.push(ty.clone());
        }
        hir::Type::RawPointer { inner, .. } => collect_callback_types(program, inner, output)?,
        _ => {
            c_type(program, ty)?;
        }
    }
    Ok(())
}

fn c_result(program: &hir::Program, ty: &hir::Type) -> Result<String, Diagnostic> {
    if matches!(ty, hir::Type::Unit) {
        Ok("void".to_owned())
    } else {
        c_type(program, ty)
    }
}

fn c_type(program: &hir::Program, ty: &hir::Type) -> Result<String, Diagnostic> {
    Ok(match ty {
        hir::Type::Unit => "void".into(),
        hir::Type::Bool => "bool".into(),
        hir::Type::Int {
            signed,
            width: Some(width),
        } if matches!(width, 8 | 16 | 32 | 64) => {
            format!("{}int{width}_t", if *signed { "" } else { "u" })
        }
        hir::Type::Int {
            signed,
            width: None,
        } => if *signed { "intptr_t" } else { "uintptr_t" }.into(),
        hir::Type::Float { width: 32 } => "float".into(),
        hir::Type::Float { width: 64 } => "double".into(),
        hir::Type::CStr => "const char *".into(),
        hir::Type::RawPointer { .. } => pointer_name(ty)?,
        hir::Type::CFunction(_, _) => callback_name(ty)?,
        hir::Type::Struct(id, arguments)
            if arguments.is_empty()
                && program
                    .structs
                    .get(id.0)
                    .is_some_and(|declaration| declaration.c_abi) =>
        {
            record_name(&program.structs[id.0])?
        }
        _ => {
            return Err(Diagnostic::new(
                DiagnosticKind::Backend,
                "type has no stable DISP C header representation",
                Span::point(1, 1),
            )
            .with_help(
                "use C ABI scalars, CStr parameters, CFunction signatures, exported C structs, or raw pointers to C ABI types",
            ));
        }
    })
}

fn record_name(declaration: &hir::Struct) -> Result<String, Diagnostic> {
    if !declaration.c_abi {
        return Err(error(
            "internal C header record request was not an exported C struct",
        ));
    }
    Ok(format!("disp_c_{}", declaration.name))
}

fn emit_record_definitions(program: &hir::Program, output: &mut String) -> Result<(), Diagnostic> {
    let target = Target::host()?;
    let mut emitted = HashSet::new();
    let mut active = HashSet::new();
    for declaration in program
        .structs
        .iter()
        .filter(|declaration| declaration.c_abi)
    {
        emit_record_definition(
            program,
            target,
            declaration.id.0,
            output,
            &mut emitted,
            &mut active,
        )?;
    }
    Ok(())
}

fn emit_record_definition(
    program: &hir::Program,
    target: Target,
    id: usize,
    output: &mut String,
    emitted: &mut HashSet<usize>,
    active: &mut HashSet<usize>,
) -> Result<(), Diagnostic> {
    if emitted.contains(&id) {
        return Ok(());
    }
    if !active.insert(id) {
        return Err(error(
            "exported C structs cannot contain a recursive by-value record cycle",
        ));
    }
    let declaration = program
        .structs
        .get(id)
        .ok_or_else(|| error("unknown exported C struct identity"))?;
    for field in &declaration.fields {
        if let hir::Type::Struct(dependency, arguments) = &field.ty {
            if !arguments.is_empty() {
                return Err(error("exported C structs cannot contain generic records"));
            }
            emit_record_definition(program, target, dependency.0, output, emitted, active)?;
        }
    }
    let ty = hir::Type::Struct(declaration.id, vec![]);
    let concrete_layout = layout::LayoutEngine::new(target, program).layout(&ty)?;
    let name = record_name(declaration)?;
    let storage_name = native_types::name(&ty);
    writeln!(output, "struct {storage_name} {{").unwrap();
    for field in &declaration.fields {
        let field_type = c_type(program, &field.ty)?;
        let internal_name = format!("f{}", field.index);
        if field.name == internal_name {
            writeln!(output, "{field_type} {internal_name};").unwrap();
        } else {
            writeln!(
                output,
                "union {{ {field_type} {internal_name}; {field_type} {}; }};",
                field.name
            )
            .unwrap();
        }
    }
    writeln!(output, "}};").unwrap();
    for (field, offset) in declaration.fields.iter().zip(&concrete_layout.fields) {
        writeln!(
            output,
            "DISP_C_STATIC_ASSERT(offsetof({name}, {}) == {offset}, \"DISP C ABI field offset mismatch: {}.{}\");",
            field.name, declaration.name, field.name
        )
        .unwrap();
    }
    writeln!(
        output,
        "DISP_C_STATIC_ASSERT(sizeof({name}) == {}, \"DISP C ABI size mismatch: {}\");",
        concrete_layout.size, declaration.name
    )
    .unwrap();
    writeln!(
        output,
        "DISP_C_STATIC_ASSERT(DISP_C_ALIGNOF({name}) == {}, \"DISP C ABI alignment mismatch: {}\");",
        concrete_layout.align, declaration.name
    )
    .unwrap();
    active.remove(&id);
    emitted.insert(id);
    Ok(())
}

fn pointer_name(ty: &hir::Type) -> Result<String, Diagnostic> {
    let hir::Type::RawPointer { mutable, inner } = ty else {
        return Err(error(
            "internal C header pointer request was not a raw pointer",
        ));
    };
    Ok(format!(
        "disp_c_{}ptr_{}",
        if *mutable { "mut_" } else { "" },
        type_code(inner)
    ))
}

fn callback_name(ty: &hir::Type) -> Result<String, Diagnostic> {
    if !matches!(ty, hir::Type::CFunction(_, _)) {
        return Err(error(
            "internal C header callback request was not a C function",
        ));
    }
    Ok(format!("disp_c_fn_{}", type_code(ty)))
}

fn type_code(ty: &hir::Type) -> String {
    match ty {
        hir::Type::Unit => "void".into(),
        hir::Type::Bool => "bool".into(),
        hir::Type::Int { signed, width } => format!(
            "{}{}",
            if *signed { "i" } else { "u" },
            width.map_or_else(|| "size".into(), |width| width.to_string())
        ),
        hir::Type::Float { width } => format!("f{width}"),
        hir::Type::CStr => "cstr".into(),
        hir::Type::Struct(id, arguments) if arguments.is_empty() => {
            format!("record_{}", id.0)
        }
        hir::Type::RawPointer { mutable, inner } => {
            format!("{}p_{}", if *mutable { "m" } else { "c" }, type_code(inner))
        }
        hir::Type::CFunction(parameters, result) => format!(
            "CF{}_{}",
            parameters
                .iter()
                .map(type_code)
                .collect::<Vec<_>>()
                .join("_"),
            type_code(result)
        ),
        _ => "unsupported".into(),
    }
}

fn pointer_depth(ty: &hir::Type) -> usize {
    match ty {
        hir::Type::RawPointer { inner, .. } => 1 + pointer_depth(inner),
        _ => 0,
    }
}

fn callback_depth(ty: &hir::Type) -> usize {
    match ty {
        hir::Type::CFunction(parameters, result) => {
            1 + parameters
                .iter()
                .chain(std::iter::once(&**result))
                .map(callback_depth)
                .max()
                .unwrap_or(0)
        }
        _ => 0,
    }
}

fn error(message: &str) -> Diagnostic {
    Diagnostic::new(DiagnosticKind::Backend, message, Span::point(1, 1))
}
