/* Generated by DISP. Do not edit. */
#ifndef DISP_C_ABI_V1_H
#define DISP_C_ABI_V1_H
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#define DISP_C_ABI_VERSION 1u
#if CHAR_BIT != 8
#error "DISP C ABI requires 8-bit bytes"
#endif
#if defined(__cplusplus)
extern "C" {
#endif
#if defined(__cplusplus)
static_assert(sizeof(bool) == 1, "DISP bool ABI mismatch");
#else
_Static_assert(sizeof(bool) == 1, "DISP bool ABI mismatch");
#endif
/* DISP library: process */
int32_t abs(int32_t arg1);
#if defined(__cplusplus)
}
#endif
#endif /* DISP_C_ABI_V1_H */
