/* Generated by DISP. Do not edit. */
#ifndef DISP_C_ABI_V1_H
#define DISP_C_ABI_V1_H
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#define DISP_C_ABI_VERSION 1u
#if CHAR_BIT != 8
#error "DISP C ABI requires 8-bit bytes"
#endif
#if defined(__cplusplus)
extern "C" {
#endif
#if defined(__cplusplus)
static_assert(sizeof(bool) == 1, "DISP bool ABI mismatch");
#else
_Static_assert(sizeof(bool) == 1, "DISP bool ABI mismatch");
#endif
#define DISP_C_STATUS_OK 0
#define DISP_C_STATUS_PANIC 1
#define DISP_C_STATUS_INVALID_ARGUMENT 2
#define DISP_C_STATUS_THREAD_NOT_ATTACHED 3
#define DISP_C_STATUS_THREAD_ALREADY_ATTACHED 4
#define DISP_C_STATUS_THREAD_BUSY 5
#if defined(_WIN32)
#define DISP_C_API __declspec(dllimport)
#else
#define DISP_C_API __attribute__((visibility("default")))
#endif
DISP_C_API const char *disp_c_last_error(void);
DISP_C_API int32_t disp_c_thread_attach(void);
DISP_C_API int32_t disp_c_thread_detach(void);
typedef int32_t (*disp_c_callback_example_add)(int32_t arg1, int32_t arg2, int32_t *out_result);
DISP_C_API int32_t example_add(int32_t arg1, int32_t arg2, int32_t *out_result);
typedef int32_t (*disp_c_callback_example_divide)(int32_t arg1, int32_t arg2, int32_t *out_result);
DISP_C_API int32_t example_divide(int32_t arg1, int32_t arg2, int32_t *out_result);
#if defined(__cplusplus)
}
#endif
#endif /* DISP_C_ABI_V1_H */
