[package]
name = "disp"
version = "0.1.0"
edition = "2024"

[features]
fuzzing = []

[dependencies]
unicode-ident = "1.0"
unicode-normalization = "0.1"
sha2 = "0.10"
hmac = "0.12.1"
hkdf = "0.12.4"
getrandom = "0.4.3"
subtle = "2.6.1"
zeroize = "1.9.0"
aes-gcm-siv = { version = "0.12.0", default-features = false, features = ["aes", "alloc", "zeroize"] }
ed25519-dalek = "3.0.0"
argon2 = { version = "0.5.3", default-features = false, features = ["alloc", "password-hash", "zeroize"] }
native-tls = "0.2.18"
url = "2.5.8"
httparse = "1.10.1"
libc = "0.2"
disp-crypto-native = { path = "crypto-native" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Isolation", "Win32_Storage_FileSystem", "Win32_System_Console", "Win32_System_JobObjects", "Win32_System_Pipes", "Win32_System_SystemServices", "Win32_System_Threading", "Win32_System_WindowsProgramming"] }
