use disp::check_source;
use std::{fs, path::Path};

const RULE_EVIDENCE: &[(&str, &str, &str)] = &[
    (
        "DISP-CORE-0001",
        "tests/cli.rs",
        "run_and_check_commands_use_the_full_pipeline",
    ),
    (
        "DISP-CORE-0002",
        "src/lexer.rs",
        "lexes_keywords_identifiers_and_unicode",
    ),
    (
        "DISP-CORE-0003",
        "tests/fuzz_smoke.rs",
        "complete_frontend_fuzz_smoke_never_panics",
    ),
    (
        "DISP-CORE-0004",
        "tests/specification.rs",
        "reserved_future_words_have_no_core_grammar",
    ),
    (
        "DISP-CORE-0005",
        "src/parser.rs",
        "rejects_pathological_nesting_without_panicking",
    ),
    (
        "DISP-CORE-0006",
        "tests/modules.rs",
        "conflicting_wildcard_imports_fail_instead_of_guessing",
    ),
    (
        "DISP-CORE-0007",
        "tests/adts.rs",
        "nominal_types_do_not_unify_structurally",
    ),
    (
        "DISP-CORE-0008",
        "tests/backend.rs",
        "native_checked_overflow_has_controlled_failure",
    ),
    (
        "DISP-CORE-0009",
        "tests/ownership.rs",
        "definite_initialization_merges_control_flow",
    ),
    (
        "DISP-CORE-0010",
        "src/interpreter.rs",
        "return_break_and_continue_propagate_correctly",
    ),
    (
        "DISP-CORE-0011",
        "tests/callables.rs",
        "closures_capture_shared_mutable_and_moved_state_differentially",
    ),
    (
        "DISP-CORE-0012",
        "tests/patterns.rs",
        "nested_finite_patterns_are_proven_exhaustive",
    ),
    (
        "DISP-CORE-0013",
        "tests/generics.rs",
        "generic_trait_implementations_instantiate_and_overlap_is_rejected",
    ),
    (
        "DISP-CORE-0014",
        "tests/dynamic_places.rs",
        "indexed_loans_block_owner_mutation_moves_and_lifetime_escape",
    ),
    (
        "DISP-CORE-0015",
        "tests/ffi.rs",
        "ffi_calls_require_unsafe_and_signatures_reject_owned_or_borrowed_abi_values",
    ),
    (
        "DISP-CORE-0016",
        "tests/async.rs",
        "suspension_resumes_without_repeating_prior_side_effects",
    ),
    (
        "DISP-CORE-0017",
        "tests/data.rs",
        "data_schemas_are_nominal_and_reach_hir_mir",
    ),
    (
        "DISP-CORE-0018",
        "tests/cli.rs",
        "native_run_cache_reuses_unchanged_builds_and_tracks_imports",
    ),
    (
        "DISP-CORE-0019",
        "tests/diagnostics.rs",
        "compiler_stages_have_stable_codes_and_exact_spans",
    ),
    (
        "DISP-CORE-0020",
        "tests/effects.rs",
        "explicit_and_inferred_effect_contracts_are_checked_and_reported",
    ),
    (
        "DISP-CORE-0021",
        "tests/expansion.rs",
        "map_substitution_is_hygienic_and_preserves_call_site_names",
    ),
    (
        "DISP-CORE-0022",
        "tests/generics.rs",
        "associated_type_projection_is_resolved_by_the_selected_implementation",
    ),
    (
        "DISP-CORE-0023",
        "tests/patterns.rs",
        "or_patterns_expand_nested_alternatives_with_one_binding_contract",
    ),
    (
        "DISP-CORE-0024",
        "tests/errors.rs",
        "typed_result_propagation_is_exact_and_differential",
    ),
    (
        "DISP-CORE-0025",
        "tests/errors.rs",
        "mir_failure_edge_moves_error_before_exactly_once_cleanup",
    ),
    (
        "DISP-CORE-0026",
        "tests/compatibility.rs",
        "legacy_and_explicit_edition_one_have_identical_behavior",
    ),
    (
        "DISP-CORE-0027",
        "tests/compatibility.rs",
        "migration_pins_compatibility_without_rewriting_source",
    ),
    (
        "DISP-CORE-0028",
        "tests/ownership_model.rs",
        "aggregate_borrows_preserve_safe_input_origins_and_active_loans",
    ),
    (
        "DISP-CORE-0029",
        "tests/memory_safety_model.rs",
        "representative_safe_memory_program_passes_native_sanitizers",
    ),
    (
        "DISP-CORE-0030",
        "tests/unsafe_containment.rs",
        "nested_blocks_cannot_widen_an_enclosing_contract",
    ),
    (
        "DISP-CORE-0031",
        "tests/raw_pointer_safety.rs",
        "checked_offsets_and_accesses_fail_before_native_undefined_behavior",
    ),
    (
        "DISP-CORE-0032",
        "tests/concurrency.rs",
        "bounded_channels_stress_multiple_producers_and_drain_after_close",
    ),
    (
        "DISP-CORE-0033",
        "tests/tasks.rs",
        "cancelling_a_parent_cancels_pending_nested_tasks_before_later_side_effects",
    ),
    (
        "DISP-CORE-0034",
        "tests/resource_limits.rs",
        "native_runtime_threads_share_one_process_quota",
    ),
    (
        "DISP-CORE-0035",
        "tests/modules.rs",
        "compiler_extension_manifests_fail_closed_with_security_guidance",
    ),
    (
        "DISP-CORE-0036",
        "tests/components.rs",
        "component_profile_limits_fail_closed_in_isolated_children",
    ),
    (
        "DISP-CORE-0037",
        "tests/components.rs",
        "linux_component_profile_denies_network_syscalls",
    ),
    (
        "DISP-CORE-0038",
        "tests/components.rs",
        "windows_component_is_appcontainer_and_denies_network_and_host_files",
    ),
    (
        "DISP-CORE-0039",
        "tests/components.rs",
        "windows_component_is_appcontainer_and_denies_network_and_host_files",
    ),
    (
        "DISP-CORE-0040",
        "tests/crypto_language.rs",
        "native_randomness_matches_interpreter_and_uses_the_os_provider",
    ),
    (
        "DISP-CORE-0041",
        "tests/crypto_language.rs",
        "native_secret_bytes_match_interpreter_and_zeroize_before_release",
    ),
    (
        "DISP-CORE-0042",
        "tests/crypto_language.rs",
        "native_sha256_and_hmac_use_platform_providers_and_match_the_interpreter",
    ),
    (
        "DISP-CORE-0043",
        "tests/crypto_language.rs",
        "native_hkdf_sha256_matches_rfc5869_and_zeroizes_intermediates",
    ),
    (
        "DISP-CORE-0044",
        "tests/crypto_native_abi.rs",
        "native_crypto_abi_seals_opens_and_authenticates_before_output",
    ),
    (
        "DISP-CORE-0045",
        "tests/crypto_language.rs",
        "interpreter_authenticated_encryption_is_opaque_and_fail_closed",
    ),
    (
        "DISP-CORE-0046",
        "tests/crypto_language.rs",
        "ed25519_signatures_are_opaque_strict_and_native_differential",
    ),
    (
        "DISP-CORE-0047",
        "tests/crypto_language.rs",
        "argon2id_password_hashing_is_fixed_policy_and_native_differential",
    ),
    (
        "DISP-CORE-0048",
        "tests/crypto_language.rs",
        "aead_envelope_format_is_versioned_canonical_and_native_differential",
    ),
    (
        "DISP-CORE-0049",
        "tests/crypto_language.rs",
        "ed25519_signatures_are_opaque_strict_and_native_differential",
    ),
    (
        "DISP-CORE-0050",
        "tests/crypto_native_abi.rs",
        "native_crypto_abi_generates_signs_and_strictly_verifies_ed25519",
    ),
    (
        "DISP-CORE-0051",
        "tests/crypto_language.rs",
        "ed25519_signatures_are_opaque_strict_and_native_differential",
    ),
    (
        "DISP-CORE-0052",
        "tests/crypto_language.rs",
        "ed25519_lifecycle_enforces_activation_expiry_and_revocation_differentially",
    ),
    (
        "DISP-CORE-0053",
        "src/crypto_keystore.rs",
        "provider_sdk_dispatches_only_opaque_handles_and_messages",
    ),
    (
        "DISP-CORE-0054",
        "tests/supply_chain.rs",
        "dependency_audit_is_pinned_scheduled_and_fail_closed",
    ),
    (
        "DISP-CORE-0055",
        "tests/supply_chain.rs",
        "libfuzzer_targets_are_pinned_and_continuously_exercised",
    ),
    (
        "DISP-CORE-0056",
        "tests/supply_chain.rs",
        "release_binaries_embed_and_verify_locked_dependency_provenance",
    ),
    (
        "DISP-CORE-0057",
        "tests/security_governance.rs",
        "compiler_unsafe_code_stays_inside_the_audited_boundary_inventory",
    ),
    (
        "DISP-CORE-0058",
        "tests/supply_chain.rs",
        "rust_asan_regressions_are_pinned_and_fail_closed",
    ),
    (
        "DISP-CORE-0059",
        "tests/supply_chain.rs",
        "release_sboms_cover_locked_native_graphs_on_every_desktop_platform",
    ),
    (
        "DISP-CORE-0060",
        "tests/supply_chain.rs",
        "signed_release_provenance_is_scoped_and_binds_each_sbom",
    ),
    (
        "DISP-CORE-0061",
        "tests/freestanding.rs",
        "direct_freestanding_build_is_runtime_free_deterministic_and_fail_closed",
    ),
    (
        "DISP-CORE-0062",
        "src/freestanding.rs",
        "allocation_free_u16_control_flow_emits_checked_machine_code",
    ),
    (
        "DISP-CORE-0063",
        "src/freestanding.rs",
        "encoding_and_multisector_capacity_fail_closed",
    ),
    (
        "DISP-CORE-0064",
        "src/freestanding.rs",
        "wider_signed_and_boolean_values_have_exact_checked_codegen",
    ),
    (
        "DISP-CORE-0065",
        "src/freestanding.rs",
        "scalar_functions_preserve_nested_arguments_returns_and_recursive_frames",
    ),
    (
        "DISP-CORE-0066",
        "src/freestanding.rs",
        "structured_loops_bind_break_and_continue_to_the_innermost_scope",
    ),
    (
        "DISP-CORE-0067",
        "src/freestanding.rs",
        "scalar_functions_preserve_nested_arguments_returns_and_recursive_frames",
    ),
    (
        "DISP-CORE-0068",
        "src/freestanding.rs",
        "exact_u8_values_use_compact_storage_checked_math_and_safe_calls",
    ),
    (
        "DISP-CORE-0069",
        "src/freestanding32.rs",
        "protected32_bootstrap_is_flat_deterministic_and_fail_closed",
    ),
    (
        "DISP-CORE-0070",
        "src/freestanding32.rs",
        "protected32_bootstrap_is_flat_deterministic_and_fail_closed",
    ),
    (
        "DISP-CORE-0071",
        "src/freestanding32.rs",
        "protected32_u32_control_flow_is_checked_and_uses_memory_above_one_mibibyte",
    ),
    (
        "DISP-CORE-0072",
        "src/freestanding32.rs",
        "protected32_exact_compact_and_signed_widths_fail_closed",
    ),
    (
        "DISP-CORE-0073",
        "src/freestanding32.rs",
        "protected32_functions_preserve_nested_and_recursive_frames",
    ),
    (
        "DISP-CORE-0074",
        "src/freestanding32.rs",
        "protected32_fixed_arrays_use_exact_storage_checked_indices_and_recursive_frames",
    ),
    (
        "DISP-CORE-0075",
        "src/freestanding32.rs",
        "protected32_device_io_requires_explicit_authority_and_emits_exact_port_instructions",
    ),
    (
        "DISP-CORE-0076",
        "src/freestanding32.rs",
        "protected32_installs_bounded_exception_gates_and_a_known_state_handler",
    ),
    (
        "DISP-CORE-0077",
        "src/freestanding32.rs",
        "protected32_enables_bounded_identity_paging_with_an_unmapped_null_page",
    ),
    (
        "DISP-CORE-0078",
        "src/freestanding64.rs",
        "x86_64_bootstrap_checks_cpu_builds_four_level_paging_and_enters_long_mode",
    ),
    (
        "DISP-CORE-0079",
        "src/freestanding64.rs",
        "x86_64_checked_scalars_use_bounded_absolute_locals_and_long_mode_stack_encodings",
    ),
    (
        "DISP-CORE-0080",
        "src/freestanding64.rs",
        "x86_64_functions_snapshot_guard_and_restore_recursive_scalar_frames",
    ),
    (
        "DISP-CORE-0081",
        "src/freestanding64.rs",
        "x86_64_fixed_arrays_use_exact_storage_checked_indices_and_recursive_frames",
    ),
    (
        "DISP-CORE-0082",
        "src/freestanding64.rs",
        "x86_64_device_io_requires_explicit_authority_and_emits_exact_port_instructions",
    ),
    (
        "DISP-CORE-0083",
        "src/freestanding64.rs",
        "x86_64_nx_paging_whitelists_only_the_bounded_stage_for_execution",
    ),
    (
        "DISP-CORE-0084",
        "src/freestanding64.rs",
        "x86_64_idt_routes_security_critical_faults_to_distinct_fail_closed_handlers",
    ),
    (
        "DISP-CORE-0085",
        "src/freestanding64.rs",
        "x86_64_pic_is_remapped_fully_masked_and_routed_before_user_code",
    ),
    (
        "DISP-CORE-0086",
        "src/freestanding64.rs",
        "x86_64_timer_capability_installs_one_bounded_100_hz_irq_source",
    ),
    (
        "DISP-CORE-0087",
        "src/freestanding_aarch64.rs",
        "aarch64_image_has_checked_scalar_control_and_deterministic_utf8_data",
    ),
    (
        "DISP-CORE-0088",
        "src/freestanding_aarch64.rs",
        "aarch64_scalar_profile_rejects_unsupported_or_unbounded_programs",
    ),
    (
        "DISP-CORE-0089",
        "src/freestanding_aarch64.rs",
        "aarch64_exact_widths_use_compact_storage_checked_signed_math_and_scalar_output",
    ),
    (
        "DISP-CORE-0090",
        "src/freestanding_aarch64.rs",
        "aarch64_functions_preserve_recursive_exact_frames_and_guard_the_stack",
    ),
    (
        "DISP-CORE-0091",
        "src/freestanding_aarch64.rs",
        "aarch64_fixed_arrays_use_exact_storage_checked_indices_and_recursive_frames",
    ),
    (
        "DISP-CORE-0092",
        "src/freestanding_aarch64.rs",
        "aarch64_exception_vectors_cover_current_el_classes_and_fail_closed",
    ),
    (
        "DISP-CORE-0093",
        "src/freestanding_aarch64.rs",
        "aarch64_sparse_page_tables_enforce_wx_and_protect_translation_state",
    ),
    (
        "DISP-CORE-0094",
        "src/freestanding_aarch64.rs",
        "aarch64_dtb_prelude_discovers_pl011_validates_ram_and_patches_sparse_tables",
    ),
    (
        "DISP-CORE-0095",
        "src/freestanding_aarch64.rs",
        "aarch64_mmio_requires_device_authority_bounds_offsets_and_orders_volatile_access",
    ),
    (
        "DISP-CORE-0096",
        "tests/c_header.rs",
        "generated_header_compiles_as_c_and_cpp_and_is_written_transactionally",
    ),
    (
        "DISP-CORE-0097",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0098",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0099",
        "tests/c_callbacks.rs",
        "disp_invokes_an_imported_c_symbol_through_a_typed_callback",
    ),
    (
        "DISP-CORE-0100",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0101",
        "tests/c_registration.rs",
        "native_registration_closes_explicitly_or_at_scope_exit_exactly_once",
    ),
    (
        "DISP-CORE-0102",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0103",
        "tests/c_registration.rs",
        "threaded_provider_is_joined_before_its_context_is_released",
    ),
    (
        "DISP-CORE-0104",
        "tests/c_exports.rs",
        "disp_passes_checked_export_callbacks_to_a_threaded_c_provider",
    ),
    (
        "DISP-CORE-0105",
        "tests/c_registration.rs",
        "captured_disp_handler_runs_on_provider_thread_and_drops_after_quiescence",
    ),
    (
        "DISP-CORE-0106",
        "tests/c_registration.rs",
        "captured_disp_handler_runs_on_provider_thread_and_drops_after_quiescence",
    ),
    (
        "DISP-CORE-0107",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0108",
        "tests/c_exports.rs",
        "c_consumer_calls_shared_disp_library_and_observes_contained_failure",
    ),
    (
        "DISP-CORE-0109",
        "tests/c_header.rs",
        "generated_header_compiles_as_c_and_cpp_and_is_written_transactionally",
    ),
    (
        "DISP-CORE-0110",
        "tests/c_exports.rs",
        "contained_export_failure_rolls_back_handle_resources_in_reverse_order",
    ),
    (
        "DISP-CORE-0111",
        "tests/data.rs",
        "count_and_exists_are_typed_indexed_durable_and_differential",
    ),
    (
        "DISP-CORE-0112",
        "tests/data.rs",
        "value_aggregates_are_typed_checked_durable_and_differential",
    ),
];

fn compiler_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn specification() -> String {
    fs::read_to_string(compiler_root().join("../docs/language/SPECIFICATION_1.md"))
        .expect("the normative core specification must be present")
}

#[test]
fn every_normative_rule_has_live_named_evidence() {
    let specification = specification();
    for (rule, relative_file, symbol) in RULE_EVIDENCE {
        assert_eq!(
            specification.matches(&format!("**{rule} —")).count(),
            1,
            "{rule} must have exactly one normative definition"
        );
        assert!(
            specification.contains(&format!("| {rule} |")),
            "{rule} must appear in the evidence matrix"
        );
        let evidence = fs::read_to_string(compiler_root().join(relative_file))
            .unwrap_or_else(|error| panic!("could not read evidence {relative_file}: {error}"));
        assert!(
            evidence.contains(&format!("fn {symbol}")),
            "evidence symbol {symbol} for {rule} is missing from {relative_file}"
        );
    }

    let defined = specification.matches("**DISP-CORE-").count();
    assert_eq!(
        defined,
        RULE_EVIDENCE.len(),
        "all normative rules need evidence entries"
    );
}

#[test]
fn reserved_future_words_have_no_core_grammar() {
    for word in [
        "parallel",
        "transaction",
        "page",
        "component",
        "style",
        "state",
        "route",
        "comptime",
    ] {
        let source = format!("fn main() {{ let {word} = 1 }}");
        let error =
            check_source(&source).expect_err("reserved future word must not be an identifier");
        assert_eq!(error.span.start.line, 1);
    }
}

#[test]
fn grammar_examples_cover_semicolons_unicode_and_future_boundaries() {
    let valid = r#"
struct 値<T: Copy> { item: T }
enum Maybe<T> { Present(T), Missing }
fn identity<T: Copy>(value: T) -> T = value
fn main() {
    let answer: int = identity(42);
    let wrapped = Maybe.Present(answer)
    print(match wrapped { Present(value) => value, Missing => 0 })
}
"#;
    check_source(valid).expect("the normative grammar example must remain valid");
}
